[workspace]
members = [
    "packages/*",
    "contracts/fungible-tokens/*",
    "contracts/non-fungible-tokens/*",
    "contracts/ecosystem/*",
    "contracts/data-storage/*",
    "contracts/app/*",
    "contracts/finance/*",
    "contracts/modules/*"
]

[profile.release.package.andromeda-protocol]
codegen-units = 1
incremental = false

[profile.release.package.common]
codegen-units = 1
incremental = false

[profile.release.package.ado-base]
codegen-units = 1
incremental = false

[profile.release.package.andromeda-cw721]
codegen-units = 1

[profile.release.package.andromeda-cw20]
codegen-units = 1

[profile.release.package.andromeda-anchor-earn]
codegen-units = 1

[profile.release.package.andromeda-crowdfund]
codegen-units = 1

[profile.release]
debug = false
debug-assertions = false
opt-level = 3
rpath = false
lto = true
overflow-checks = true
panic='abort'
