[package]
name = "andromeda-mirror"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.0.0"
cw-storage-plus = "0.13.2"
cw2 = "0.13.2"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
mirror-protocol = "2.1.1"
terraswap = {version = "2.4.0"}
cw20 = "0.13.2"
cw-asset = "2.0.0"

andromeda-ecosystem = { version = "0.1.0", path = "../../../packages/andromeda-ecosystem" }
common = { version = "0.1.0", path = "../../../packages/common" }
ado-base = { path = "../../../packages/ado-base", version = "0.1.0", features = ["primitive", "withdraw"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
