[package]
name = "andromeda-anchor-earn"
version = "0.1.0"
authors = ["AndrewPochapsky <andrew.pochapsky@gmail.com>"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = "1.0.0"
cw-storage-plus = "0.13.2"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
cw20 = "0.13.2"
cw2 = "0.13.2"
cw-asset = "2.0.0"
moneymarket = "0.3.0"

andromeda-ecosystem = { version = "0.1.0", path = "../../../packages/andromeda-ecosystem" }
common = { version = "0.1.0", path = "../../../packages/common" }
ado-base = { path = "../../../packages/ado-base", version = "0.1.0", features = ["primitive"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
